name: Go

on:
  push:
    branches:
      - '!main' 
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd hello-world && go build -v ./...

    - name: Test
      run: cd hello-world && go test -v ./...
    
  promoteToMain:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: '!main'
